### ISSUE TITLE
[Init] 초기 세팅

### ISSUE THREAD

**Issue by jungwoo3490** [SimSimS-ToyProject-TEAM3/SimSimS-ToyProject-TEAM3#1]
## 🛠 Issue
프로젝트 초기 세팅을 진행할 예정입니다!!

## 📝 To-do

- [x] Next.js 14버전 프로젝트 생성
- [x] eslint 세팅
- [x] prettier 세팅
- [x] stylelint 세팅
- [x] husky & lint-staged 세팅
- [x] emotion & globalStyle 세팅
