### ISSUE TITLE
[design] Login 페이지 Token 입력 컨테이너 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by jungwoo3490** [SimSimS-ToyProject-TEAM3/SimSimS-ToyProject-TEAM3#2]
## 🛠 Issue

로그인 페이지에서 토큰 입력하는 컨테이너 컴포넌트 UI를 구현할 예정입니다.

## 📝 To-do

- [x] Login Page 컴포넌트 기본 스타일링 (배경색 & 중앙정렬)
- [x] 토큰 입력 컨테이너 컴포넌트 생성
- [x] 토큰 입력 컨테이너 UI 구현
