### ISSUE TITLE
[feat] Follow List 페이지 맞팔현황 GET API 연결

### ISSUE THREAD

**Issue by simeunseo** [SimSimS-ToyProject-TEAM3/SimSimS-ToyProject-TEAM3#3]
## 🛠 Issue

팔로우 목록을 가져오고, 맞팔이 되어있는 사람과 맞팔이 되어있지 않은 사람을 구별하여 렌더링한다.

## 📝 To-do

- [x] 팔로우 목록 GET
- [x] 맞팔아닌 사람 목록 리스팅
- [x] 맞팔인 사람 목록 리스팅
